// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Solaris.Web.CrewApi.Infrastructure.Data;

namespace Solaris.Web.CrewApi.Presentation.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Solaris.Web.CrewApi.Core.Models.Entities.CrewMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ExplorersTeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ExplorersTeamId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CrewMembers");

                    b.HasDiscriminator<byte>("Type");
                });

            modelBuilder.Entity("Solaris.Web.CrewApi.Core.Models.Entities.ExplorersTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DepartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExplorersTeams");
                });

            modelBuilder.Entity("Solaris.Web.CrewApi.Core.Models.Entities.Shuttle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ExplorersTeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ShipNumber")
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("ExplorersTeamId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Shuttles");
                });

            modelBuilder.Entity("Solaris.Web.CrewApi.Core.Models.Entities.Captain", b =>
                {
                    b.HasBaseType("Solaris.Web.CrewApi.Core.Models.Entities.CrewMember");

                    b.Property<sbyte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.HasDiscriminator().HasValue((byte)0);
                });

            modelBuilder.Entity("Solaris.Web.CrewApi.Core.Models.Entities.Robot", b =>
                {
                    b.HasBaseType("Solaris.Web.CrewApi.Core.Models.Entities.CrewMember");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CurrentPlanetId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("CurrentStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ProductNumber")
                        .HasColumnType("varchar(256)");

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("Solaris.Web.CrewApi.Core.Models.Entities.CrewMember", b =>
                {
                    b.HasOne("Solaris.Web.CrewApi.Core.Models.Entities.ExplorersTeam", "ExplorersTeam")
                        .WithMany("CrewMembers")
                        .HasForeignKey("ExplorersTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Solaris.Web.CrewApi.Core.Models.Entities.Shuttle", b =>
                {
                    b.HasOne("Solaris.Web.CrewApi.Core.Models.Entities.ExplorersTeam", "ExplorersTeam")
                        .WithOne("Shuttle")
                        .HasForeignKey("Solaris.Web.CrewApi.Core.Models.Entities.Shuttle", "ExplorersTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
